capturing
captureExceptionsDuring: aBlock
	self captureExceptionsDuring: aBlock in: [ :event | ]