capturing
captureException: anException
	^ self default captureException: anException